import { v4 as uuidv4 } from "uuid";

export const tracks = [
  {
    cover: "/tracks/1_1 - Bad Habits - Ed Sheeran (320).jpg",
    artist: "1_1",
    title: "Bad Habits",
    source: "/tracks/1_1 - Bad Habits - Ed Sheeran (320).mp3",
    uuid: uuidv4(),
    active: true,
  },
  {
    cover: "/tracks/1_1 - Be Together - BCBC (320).jpg",
    artist: "1_1",
    title: "Be Together",
    source: "/tracks/1_1 - Be Together - BCBC (320).mp3",
    uuid: uuidv4(),
    active: false,
  },
  {
    cover: "/tracks/1_1 - Easy On Me - Adele (320).jpg",
    artist: "1_1",
    title: "Easy On Me",
    source: "/tracks/1_1 - Easy On Me - Adele (320).mp3",
    uuid: uuidv4(),
    active: false,
  },
  {
    cover: "/tracks/1_1 - In Heat (Hasegawa Remix) - Hasegawa (320).jpg",
    artist: "1_1",
    title: "In Heat (Hasegawa Remix)",
    source: "/tracks/1_1 - In Heat (Hasegawa Remix) - Hasegawa (320).mp3",
    uuid: uuidv4(),
    active: false,
  },
  {
    cover: "/tracks/1_1 - Intro - The xx (320).jpg",
    artist: "1_1",
    title: "Intro",
    source: "/tracks/1_1 - Intro - The xx (320).mp3",
    uuid: uuidv4(),
    active: false,
  },
  {
    cover: "/tracks/1_1 - Love Tonight - Shouse (320).jpg",
    artist: "1_1",
    title: "Love Tonight",
    source: "/tracks/1_1 - Love Tonight - Shouse (320).mp3",
    uuid: uuidv4(),
    active: false,
  },
  {
    cover: "/tracks/1_1 - No Lie - Sean Paul  Dua Lipa (320).jpg",
    artist: "1_1",
    title: "No Lie",
    source: "/tracks/1_1 - No Lie - Sean Paul  Dua Lipa (320).mp3",
    uuid: uuidv4(),
    active: false,
  },
  {
    cover: "/tracks/1_1 - Radioactive - Coopex  Yohan Gerber  Lunis (320).jpg",
    artist: "1_1",
    title: "Radioactive",
    source: "/tracks/1_1 - Radioactive - Coopex  Yohan Gerber  Lunis (320).mp3",
    uuid: uuidv4(),
    active: false,
  },
  {
    cover: "/tracks/1_1 - Skyfall - Adele (320).jpg",
    artist: "1_1",
    title: "Skyfall",
    source: "/tracks/1_1 - Skyfall - Adele (320).mp3",
    uuid: uuidv4(),
    active: false,
  },
  {
    cover: "/tracks/1_1 - Steklyannaya - Guma (320).jpg",
    artist: "1_1",
    title: "Steklyannaya",
    source: "/tracks/1_1 - Steklyannaya - Guma (320).mp3",
    uuid: uuidv4(),
    active: false,
  },
  {
    cover: "/tracks/1_1 - Sweet Dreams - Trinix (320).jpg",
    artist: "1_1",
    title: "Sweet Dreams",
    source: "/tracks/1_1 - Sweet Dreams - Trinix (320).mp3",
    uuid: uuidv4(),
    active: false,
  },
  {
    cover: "/tracks/1_1 - Take You On - James Mercy  PhiloSofie (320).jpg",
    artist: "1_1",
    title: "Take You On",
    source: "/tracks/1_1 - Take You On - James Mercy  PhiloSofie (320).mp3",
    uuid: uuidv4(),
    active: false,
  },
  {
    cover: "/tracks/1_1 - The Search - NF (320).jpg",
    artist: "1_1",
    title: "The Search",
    source: "/tracks/1_1 - The Search - NF (320).mp3",
    uuid: uuidv4(),
    active: false,
  },
  {
    cover: "/tracks/1_1 - The Tradition - Halsey (320).jpg",
    artist: "1_1",
    title: "The Tradition",
    source: "/tracks/1_1 - The Tradition - Halsey (320).mp3",
    uuid: uuidv4(),
    active: false,
  },
  {
    cover: "/tracks/1_1 - Venom - Icon For Hire (320).jpg",
    artist: "1_1",
    title: "Venom",
    source: "/tracks/1_1 - Venom - Icon For Hire (320).mp3",
    uuid: uuidv4(),
    active: false,
  },
  {
    cover: "/tracks/1_10 - Believer - Imagine Dragons (320).jpg",
    artist: "1_10",
    title: "Believer",
    source: "/tracks/1_10 - Believer - Imagine Dragons (320).mp3",
    uuid: uuidv4(),
    active: false,
  },
  {
    cover: "/tracks/1_10 - Gonna Be U and Me - Better Than Chocolate (320).jpg",
    artist: "1_10",
    title: "Gonna Be U and Me",
    source:
      "/tracks/1_10 - Gonna Be U and Me - Better Than Chocolate (320).mp3",
    uuid: uuidv4(),
    active: false,
  },
  {
    cover: "/tracks/1_10 - Without Me - Eminem (320).jpg",
    artist: "1_10",
    title: "Without Me",
    source: "/tracks/1_10 - Without Me - Eminem (320).mp3",
    uuid: uuidv4(),
    active: false,
  },
  {
    cover: "/tracks/1_11 - Levitating - Dua Lipa (320).jpg",
    artist: "1_11",
    title: "Levitating",
    source: "/tracks/1_11 - Levitating - Dua Lipa (320).mp3",
    uuid: uuidv4(),
    active: false,
  },
  {
    cover:
      "/tracks/1_11 - Lisa Lisa - Tony Richards And The K-Man Band (320).jpg",
    artist: "1_11",
    title: "Lisa Lisa",
    source:
      "/tracks/1_11 - Lisa Lisa - Tony Richards And The K-Man Band (320).mp3",
    uuid: uuidv4(),
    active: false,
  },
  {
    cover:
      "/tracks/1_13 - Venom (Music From The Motion Picture) - Eminem (320).jpg",
    artist: "1_13",
    title: "Venom (Music From The Motion Picture)",
    source:
      "/tracks/1_13 - Venom (Music From The Motion Picture) - Eminem (320).mp3",
    uuid: uuidv4(),
    active: false,
  },
  {
    cover: "/tracks/1_14 - Aerials - System of a Down (320).jpg",
    artist: "1_14",
    title: "Aerials",
    source: "/tracks/1_14 - Aerials - System of a Down (320).mp3",
    uuid: uuidv4(),
    active: false,
  },
  {
    cover: "/tracks/1_18 - Surrender - Elvis Presley (FLAC).jpg",
    artist: "1_18",
    title: "Surrender",
    source: "/tracks/1_18 - Surrender - Elvis Presley (FLAC).mp3",
    uuid: uuidv4(),
    active: false,
  },
  {
    cover:
      "/tracks/1_1_Outside_feat_Ellie_Goulding_Calvin_Harris_Ellie_Goulding_320.jpg",
    artist: "1_1_Outside_feat_Ellie_Goulding_Calvin_Harris_Ellie_Goulding_320",
    title: "Outside",
    source:
      "/tracks/1_1_Outside_feat_Ellie_Goulding_Calvin_Harris_Ellie_Goulding_320.mp3",
    uuid: uuidv4(),
    active: false,
  },
  {
    cover: "/tracks/1_23 - Hallucinate - Dua Lipa (320).jpg",
    artist: "1_23",
    title: "Hallucinate",
    source: "/tracks/1_23 - Hallucinate - Dua Lipa (320).mp3",
    uuid: uuidv4(),
    active: false,
  },
  {
    cover: "/tracks/1_27 - drivers license - Olivia Rodrigo (320).jpg",
    artist: "1_27",
    title: "drivers license",
    source: "/tracks/1_27 - drivers license - Olivia Rodrigo (320).mp3",
    uuid: uuidv4(),
    active: false,
  },
  {
    cover: "/tracks/1_3 - Easier than Lying - Halsey (320).jpg",
    artist: "1_3",
    title: "Easier than Lying",
    source: "/tracks/1_3 - Easier than Lying - Halsey (320).mp3",
    uuid: uuidv4(),
    active: false,
  },
  {
    cover: "/tracks/1_3 - Zeit (RMX by Robot Koch) - Rammstein (320).jpg",
    artist: "1_3",
    title: "Zeit (RMX by Robot Koch)",
    source: "/tracks/1_3 - Zeit (RMX by Robot Koch) - Rammstein (320).mp3",
    uuid: uuidv4(),
    active: false,
  },
  {
    cover:
      "/tracks/1_3_Goodbye_from_the_series_Arcane_League_of_Legends_Ramsey_320.jpg",
    artist: "1_3_Goodbye_from_the_series_Arcane_League_of_Legends_Ramsey_320",
    source:
      "/tracks/1_3_Goodbye_from_the_series_Arcane_League_of_Legends_Ramsey_320.mp3",
    uuid: uuidv4(),
    active: false,
  },
  {
    cover: "/tracks/1_4 - STORY - NF (320).jpg",
    artist: "1_4",
    title: "STORY",
    source: "/tracks/1_4 - STORY - NF (320).mp3",
    uuid: uuidv4(),
    active: false,
  },
  {
    cover: "/tracks/1_5 - Delicate - Taylor Swift (320).jpg",
    artist: "1_5",
    title: "Delicate",
    source: "/tracks/1_5 - Delicate - Taylor Swift (320).mp3",
    uuid: uuidv4(),
    active: false,
  },
  {
    cover: "/tracks/1_5 - High Enough - K.Flay (320).jpg",
    artist: "1_5",
    title: "High Enough",
    source: "/tracks/1_5 - High Enough - K.Flay (320).mp3",
    uuid: uuidv4(),
    active: false,
  },
  {
    cover: "/tracks/1_5 - Oh My God - Adele (320).jpg",
    artist: "1_5",
    title: "Oh My God",
    source: "/tracks/1_5 - Oh My God - Adele (320).mp3",
    uuid: uuidv4(),
    active: false,
  },
  {
    cover: "/tracks/1_5 - Those Kinda Nights - Eminem  Ed Sheeran (320).jpg",
    artist: "1_5",
    title: "Those Kinda Nights",
    source: "/tracks/1_5 - Those Kinda Nights - Eminem  Ed Sheeran (320).mp3",
    uuid: uuidv4(),
    active: false,
  },
  {
    cover: "/tracks/1_6 - Amerika - Rammstein (320).jpg",
    artist: "1_6",
    title: "Amerika",
    source: "/tracks/1_6 - Amerika - Rammstein (320).mp3",
    uuid: uuidv4(),
    active: false,
  },
  {
    cover: "/tracks/1_6 - Black Wave - K.Flay (320).jpg",
    artist: "1_6",
    title: "Black Wave",
    source: "/tracks/1_6 - Black Wave - K.Flay (320).mp3",
    uuid: uuidv4(),
    active: false,
  },
  {
    cover: "/tracks/1_8 - Darkness - Eminem (320).jpg",
    artist: "1_8",
    title: "Darkness",
    source: "/tracks/1_8 - Darkness - Eminem (320).mp3",
    uuid: uuidv4(),
    active: false,
  },
  {
    cover: "/tracks/1_8 - Love Again - Dua Lipa (320).jpg",
    artist: "1_8",
    title: "Love Again",
    source: "/tracks/1_8 - Love Again - Dua Lipa (320).mp3",
    uuid: uuidv4(),
    active: false,
  },
  {
    cover: "/tracks/1_8 - No Goodbyes - Dua Lipa (320).jpg",
    artist: "1_8",
    title: "No Goodbyes",
    source: "/tracks/1_8 - No Goodbyes - Dua Lipa (320).mp3",
    uuid: uuidv4(),
    active: false,
  },
];

//seconds to minutes converter
export function timeConverter(time) {
  return `${Math.floor(time / 60)}:${
    Math.floor(time % 60) < 10 ? "0" : ""
  }${Math.floor(time % 60)}`;
}
